version: '3.8'
services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ../../mlflow:/mlflow


  api:
    build: ./api
    container_name: badminton_api
    volumes:
      - ../../models:/app/models
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

  app:
    build: ./app
    container_name: badminton_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
